ShopHub/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path("product/", include('product.urls'), name='product'),
    path('payment/', include("payment.urls"), name="payment"),
    path('ratting/', include('ratting.urls')),
  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from customer import views
from django.contrib.auth.views import (
      
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    
    path('',views.home, name="home"),
    path('customer/registration/', views.CustomerRegistration, name='customer-registration'),    
    path('login/', views.Login.as_view(), name= 'login'),
    path('logout/', views.logout_view, name='logout'),
    
    # reset password 
    path('password-reset/', PasswordResetView.as_view(template_name='customer/password_reset.html'),name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='customer/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='customer/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='customer/password_reset_complete.html'),name='password_reset_complete'), 

    path("show-more-review/", views.show_more_review, name="show-review"),
    path("customer-profile/", views.CustomerProfile.as_view(), name = "profile"),
    path("address/", views.show_address, name = 'address'),
    path("add-address/", views.AddAddress.as_view(), name = 'add-address'),

    # wishlist 
    path("delete-address/<int:pk>/", views.delete_address, name="delete-address"),
    path('add_to_wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path("wishlist/", views.wishlist, name='wishlist'),
    path('demo/', views.demo, name="demo")
    
    
]

product/models.py
# import lib
from django.db import models

# import model
from customer.models import Vendor, Customer
# Create your models here.

class CreateDate(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        abstract = True

class Category(models.Model):
    name = models.CharField(max_length=200)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    
class SubCategory(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    
class Product(CreateDate):
    """Product Model"""
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.FloatField()
    brand = models.CharField(max_length=30, blank=True, null=True)
    color = models.CharField(max_length=30, blank=True, null=True)
    
    ## relation
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
       
class Image(models.Model):
    image = models.ImageField(upload_to='Product_Images/', max_length=250)    
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    
    def __str__(self):  
        return str(self.image)


class Cart(models.Model):
    quantity = models.PositiveIntegerField(default=1)
    
    # relation 
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE) 
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete = models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return str(self.id)
    
    
class Wishlist(models.Model):
    
    # relation
    image = models.ForeignKey(Image, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    

customer/forms.py
from django import forms
from .models import Customer, Vendor, MultipleAddress
from django.db import models
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm

from django.utils.translation import gettext, gettext_lazy as _

class CustomerRegistrationForm(UserCreationForm):
    """Customer Registration Form """
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.CharField(required=True)
       
    class Meta:
        model = Customer
        fields = ['username', 'first_name', 'last_name', 'email', 'birth_date',
                  'phone_number','address', 'city', 'state', 'zip_code']

        
class LoginForm(forms.Form):
    """Login Form"""
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
    
class CustomerProfileForm(forms.ModelForm):
    """Customer Profile Form"""
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'email', 'birth_date', 'phone_number', 'city', 'state', 'address']
        
        widgets = {'address':forms.Textarea(attrs={'cols':34, 'rows':4})}
        
class AddAddressForm(forms.ModelForm):
    """Customer Can Add Multiple Address"""
    class Meta:
        model = MultipleAddress
        fields = ['name', 'phone_number', 'pincode', 'locality', 'address', 'city', 'state', 'landmark']
        widgets = {'address':forms.Textarea(attrs={'cols':34, 'rows':4})}
        

customer/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Customer, Vendor, MultipleAddress
from .forms import CustomerRegistrationForm
from django.views import View
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, CustomerProfileForm, AddAddressForm
from product.models import Category, Image, Product, SubCategory, Wishlist
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.mail import send_mail
from ShopHub import settings
from django.utils.decorators import method_decorator

# import ratting for product_detail
from ratting.models import Ratting

# def base(request):
#     category = Category.objects.all()
#     return render(request, 'customer/base.html', {'category':category})


def home(request):
    # before pagination  
    # category = Category.objects.all()
    # subcatagory = SubCategory.objects.all()   
    # image = Image.objects.all()
       
    # dict1={}
    # dict2={}
    # for item in category:

    #     dict1[item.name]=SubCategory.objects.filter(category__name=item.name)  
    
    # for sub in subcatagory:
    #     dict2[sub.name]=Image.objects.filter(product__sub__name=sub.name)
        
    
    # return render(request, 'customer/home.html', {'category':category, "dict1":dict1, "dict2":dict2,  'image':image, 'subactegory':subcatagory,})


    # after pagination
    print(request.user)
    product = Product.objects.all()
    category = Category.objects.all()
    subcatagory = SubCategory.objects.all()
    image = Image.objects.all()
    dict_category = {}
    dict_subcategory = {}
    for item in category:
        dict_category[item.name] = SubCategory.objects.filter(category__name=item.name)  
         
    for sub in subcatagory:
        dict_subcategory[sub.name] = Image.objects.filter(product__sub__name=sub.name)     
    dict_list = list(dict_subcategory.items())
    paginator = Paginator(dict_list, 3, orphans=1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'category': category,
        "dict1": dict_category,
        "dict2": dict_subcategory,
        'image': image,
        'subactegory': subcatagory,
        "page_obj": page_obj,
        "product": product 
    }
    return render(request, 'customer/home.html', context)


def CustomerRegistration(request):
    form = CustomerRegistrationForm()
    if request.method == "POST":
        form = CustomerRegistrationForm(request.POST)
        if form.is_valid():
            
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request, username = username, password = password)
            login(request, user)  
            return redirect('home')               
    return render(request, 'customer/customer_registration.html', {"form":form})


## login form 

# class Login(View):
#     def get(self, request):    
#         form =LoginForm
#         return render(request, 'customer/login.html', {"form":form})
#     def post(self, request):     
#         form =LoginForm(request.POST)      
#         if form.is_valid():
#             username = request.POST["username"]
#             password = request.POST["password"]    
#             user = authenticate(request, username=username, password=password)  
            
#             if user is not None:
#                 login(request, user)
#                 print(request.user)
#                 if Vendor.objects.filter(username=request.user):
#                     return HttpResponseRedirect('/product/vendor-pannel/')
#                 else:   
#                     return HttpResponseRedirect('/home/')      
#             else:
#                 # messages.info(request, 'username or password is wrong')
#                 context={
#                     "form":form,
#                     'message':"username password not match",
#                 }
#                 return render(request, 'customer/login.html',context)
                

#         else :
#           return HttpResponse("form not valid")

    ##--------------->>>>>>>>>>>>>>>
    
## updated login form
class Login(View):
    def get(self, request):    
        form =LoginForm
        return render(request, 'customer/login.html', {"form":form})
    def post(self, request):
        username = request.POST.get('username')
        username = username.lower()
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if Vendor.objects.filter(username=request.user):
                return HttpResponseRedirect('/product/vendor-pannel/')
            else:   
                return redirect('/')      
        else:
            context={     
                    'message':"username password not match",
                }
            return render(request, 'customer/login.html',context)
              
# logout view
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/login/')

# after click show more it show another 5 review
def show_more_review(request):  
      page = request.GET.get('page')
      prod_id =  request.GET.get('prod_id')  
      page = int(page)
      reviews = Ratting.objects.filter(product__id=prod_id).order_by('-id')[5 * (page - 1):5 * page]  
      data = {
         'reviews': [{'text': review.comments} for review in reviews],
            }
      return JsonResponse(data)
  
# customer can see their own profile

# class CustomerProfile(View):
#     category = Category.objects.all()
#     dict_category = {}
#     for item in category:
#         dict_category[item.name] = SubCategory.objects.filter(category__name = item.name)
        
#     def get(self, request):    
#         form =CustomerProfileForm(instance=request.user.customer if hasattr(request.user, 'customer') else None) 
#         context = {
#             'form': form, 
#             'dict1': self.dict_category
#             } 
#         return render(request, 'customer/customer_profile.html', context)
    
#     def post(self, request):
#         form = CustomerProfileForm(request.POST, instance=request.user.customer if hasattr(request.user, 'customer') else None)      
#         if form.is_valid():      
#             form.save()   
#             return HttpResponseRedirect('/customer-profile/')
        


class CustomerProfile(View):
    category = Category.objects.all()
    dict_category = {}
    for item in category:
        dict_category[item.name] = SubCategory.objects.filter(category__name=item.name)

    def get(self, request):
        print("get")
        form = CustomerProfileForm(instance=request.user.customer if hasattr(request.user, 'customer') else None)
        context = {
            'form': form,
            'dict1': self.dict_category
        }
        return render(request, 'customer/customer_profile.html', context)

    def post(self, request):
        if request.user.is_authenticated:
            print("post")
            form = CustomerProfileForm(request.POST, instance=request.user.customer if hasattr(request.user, 'customer') else None)
            if form.is_valid():
                form.save()
                print("regirection")
                return redirect('/customer-profile')
        else:
            form = CustomerProfileForm(request.POST)
            
        context = {
            'form': form,
            'dict1': self.dict_category
            }
        return render(request, 'customer/customer_profile.html', context)

        
# customer can see their address      
def show_address(request):      
        address = MultipleAddress.objects.filter(customer__username = request.user)    
        if address:   
             return render(request, 'customer/customer_show_address.html', {'address':address} )
         
        else:
            return render(request, 'customer/customer_show_address.html')

# customer can add their multiple address     
class AddAddress(View):
    def get(self, request):
        form =AddAddressForm()  
        return render(request, 'customer/customer_add_address.html', {'form':form})
       
    def post(self , request): 
        form = AddAddressForm(request.POST)   
        if form.is_valid():
            name = form.cleaned_data['name']
            phone_number = form.cleaned_data['phone_number']
            pincode = form.cleaned_data['pincode']
            locality = form.cleaned_data['locality']
            address = form.cleaned_data['address']
            city = form.cleaned_data['city']
            state = form.cleaned_data['name']
            landmark = form.cleaned_data['landmark']     
            customer = Customer.objects.get(username = request.user)
              
            # save multiple address of one customer  
            model = MultipleAddress(customer=customer, name=name, phone_number=phone_number,pincode=pincode, locality=locality, address=address, city=city, state=state, landmark=landmark)   
            model.save()     
            return redirect('/address/')


# customer can delete address 
def delete_address(request, pk):
    address = MultipleAddress(pk=pk)
    address.delete()
    return redirect('/address/')  

def wishlist(request):
    category = Category.objects.all()
    dict_category = {}
    for item in category:
        dict_category[item.name]=SubCategory.objects.filter(category__name = item.name)
        
    wishlist = Wishlist.objects.filter(customer__username = request.user)
    return render(request, 'customer/wishlist.html', {"wishlist":wishlist, "dict1":dict_category})

                                 
def add_to_wishlist(request, product_id): 

customer/templates/customer/add_address.html
{% extends "customer/base.html" %}

{% block add-address %}
{% load static %}


<div class="row">
    <div class="col-sm-3 mt-4">{% include 'customer/profile_sidebar.html' %}</div>
  
    <div class="form-display col-sm-6 mt-4">
      <h2>Addresses</h2>
   
    
  
   <form action="" method="POST">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="Save" class="btn btn-success" />
  </form>
</div>
  
        

  </div> <br><br>
  

{% endblock add-address %}

customer/templates/customer/address.html
{% extends "customer/base.html" %} {% block profile %}
{% load static %}
<style>
  .form-display {
    background-color: whitesmoke;
  }
  .ancor{
   
        top: 305px;
        right: 310px;
        position: absolute;
   
  }
  .font{
    
  }
</style>

<div class="row">
  <div class="col-sm-3 mt-4">{% include 'customer/profile_sidebar.html' %}</div>

  <div class="form-display col-sm-6 mt-4">
    <h2>Addresses</h2>
    <div>
      {% if address %}
      
      {% for add in address %}
      <div class="border border-dark" style="background: lightblue">
        {{add.name}} ,{{add.phone_number}} <br />
        {{add.address}} ,{{add.locality}} ,{{add.pincode}} ,{{add.city}} ,
        {{add.state}}
      
      <a href="{% url 'delete-address' add.id %}"> <span class="float-right mb-5 mr-3"> <i class="fa fa-trash" aria-hidden="true"></i> </span></a>
       
      </div>
      
      <br />
      {% endfor %} 
      <a class="ancor" href="{% url 'add-address' %}">
        <i class="fa fa-plus" style="margin: 3px" aria-hidden="true"></i> Add
        A New Address
      </a>

      {% else %}
      <div class ="text-center">
      <img src="{% static 'customer/images/empty_address.png' %}" alt="">

    
    </div>
    <h4 class="text-center">
      No Addresses found in your account! <br>  <br>
      Add a delivery address. <br> <br>
    </h4>
    
  
    <a class="ancor" href="{% url 'add-address' %}">
        <i class="fa fa-plus" style="margin: 3px" aria-hidden="true"></i> Add
        A New Address
      </a>
   


      {% endif %} 

      
    </div>
  </div>
</div> <br><br>

{% endblock profile %}

<form action="">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="Save" class="btn btn-success" />
  </form>

  <div class="border border-dark" style="color: blue">
    <a href="{% url 'address' %}">
      <i class="fa fa-plus" style="margin: 3px" aria-hidden="true"></i> Add
      A New Address
    </a>
  </div>

customer/templates/customer/customer_add_address.html
{% extends "customer/base.html" %}

{% block add-address %}
{% load static %}


<div class="row">
    <div class="col-sm-3 mt-4">{% include 'customer/profile_sidebar.html' %}</div>
  
    <div class="form-display col-sm-6 mt-4">
      <h2>Addresses</h2>
   
  
  
   <form action="" method="POST">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="Save" class="btn btn-success" />
  </form>
</div>
  
        

  </div> <br><br>
  

{% endblock add-address %}

customer/templates/customer/customer_show_address.html
{% extends "customer/base.html" %} {% block profile %}
{% load static %}
<style>
  .form-display {
    background-color: whitesmoke;
  }
  .ancor{
   
        top: 305px;
        right: 310px;
        position: absolute;
   
  }
  .font{
    
  }
</style>

<div class="row">
  <div class="col-sm-3 mt-4">{% include 'customer/profile_sidebar.html' %}</div>

  <div class="form-display col-sm-6 mt-4">
    <h2>Addresses</h2>
    <div>
      {% if address %}
      
      {% for add in address %}
      <div class="border border-dark" style="background: lightblue">
        {{add.name}} ,{{add.phone_number}} <br />
        {{add.address}} ,{{add.locality}} ,{{add.pincode}} ,{{add.city}} ,
        {{add.state}}
      
      <a href="{% url 'delete-address' add.id %}"> <span class="float-right mb-5 mr-3"> <i class="fa fa-trash" aria-hidden="true"></i> </span></a>
       
      </div>
      
      <br />
      {% endfor %} 
      <a class="ancor" href="{% url 'add-address' %}">
        <i class="fa fa-plus" style="margin: 3px" aria-hidden="true"></i> Add
        A New Address
      </a>

      {% else %}
      <div class ="text-center">
      <img src="{% static 'customer/images/empty_address.png' %}" alt="">

    
    </div>
    <h4 class="text-center">
      No Addresses found in your account! <br>  <br>
      Add a delivery address. <br> <br>
    </h4>
    
  
    <a class="ancor" href="{% url 'add-address' %}">
        <i class="fa fa-plus" style="margin: 3px" aria-hidden="true"></i> Add
        A New Address
      </a>
   


      {% endif %} 

      
    </div>
  </div>
</div> <br><br>

{% endblock profile %}

<form action="">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="Save" class="btn btn-success" />
  </form>

  <div class="border border-dark" style="color: blue">
    <a href="{% url 'address' %}">
      <i class="fa fa-plus" style="margin: 3px" aria-hidden="true"></i> Add
      A New Address
    </a>
  </div>

customer/templates/customer/list_product.html
{% extends "customer/base.html" %} {% block product-list %} {% load static %}

<link rel="stylesheet" href="{% static 'customer/css/list_product.css' %}" />

<h1>{{subcatagory}}</h1>

{% for ig in img %}

<div class="container my-5 mx-4">
  <div class="card flex-row flex-wrap">
    <div class="card-header border-5">
      <a href="{% url 'product-detail' ig.id %}">
        <img src="{{ ig.image.url }}" width="300px" height="400px" alt="" />

        {% comment %}
        <h4 class="card-title">{{ig.product.name}}</h4>
        <p class="card-text">{{ig.product.description}}</p>
        {% endcomment %}

        <h4 class="card-title">
          {{ig.product.name}} || Rs. <b>{{ig.product.price}}</b>
        </h4>

        <p class="card-text">{{ig.product.description}}</p>
      </a>
    </div>
  </div>
</div>
{% endfor %} {% endblock product-list %} 

customer/templates/customer/password_reset_complete.html
{%extends 'customer/base.html'%}

{%block content%}

<div class="card center">
	<p>Your password has been changed successfully. Please <a href="{% url 'login' %}">Login</a></p>
</div>
 	
{%endblock content%}

customer/templates/customer/password_reset_confirm.html
{%extends 'customer/base.html'%}

{%block content%}

<div class="center">
	<form method="post" class="card">
	  {% csrf_token %}
	  <h2>Password Reset Confirm</h2>
	  
	  {% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
	  
	  
	  <div>
	    <button type="submit" class="btn btn-primary">Reset Password</button>
	  </div>
	</form>
</div>


{%endblock content%}

customer/templates/customer/product_detail.html
{% extends "customer/base.html" %} {% block product-details %} {% load static %}

<style>
  .cont {
    display: left;
    margin: 15px;
    justify-content: space-around;
  }

  .icon{
    content: "\f004";
    display: block;
    font-size: 31px;   
  } 

  .heart-icon {
    font-size: 24px; /* Adjust the size as needed */
    color: aqua; /* Original color of the heart icon */

    transition: blue; /* Smooth color transition */

}

.wishlist-button.added .heart-icon {
    color: red;
}

.checked {
    color: orange;
}


</style>


<h1>{{img.product.sub.name}}</h1> <br>



<div class="row ml-4">
  <div class="col-sm-4" style="background-color: lightblue;">

    {% comment %} <img src="{{ img.image.url }}" width="300px" height="400" alt="not" /> {% endcomment %}


    <div >

      <div align="left"  id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
              {% for image in products.image_set.all %}
              
                  <div style="background-color:#f1ecec" class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                      <img style="width: auto;height: 700px;padding: 2px;" src="{{image.image.url}}" alt="Image not available" />
                  </div>
              {% empty %}
                  <h5>Image not available</h5>
              {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
          </a>
      </div>
  </div>
    
   







    <br/>
    <form action="/product/add-to-cart"> 
      {% csrf_token %}
        <div class="cont">
        <input type="hidden" name="prod_id" value="{{img.id}}" id="prod_id">
        <button type="submit" class="btn btn-warning shadow px-5 py-2">Add To Cart</button>
        
        
      </div>
    </form>
    <button type="submit" class="btn btn-info shadow px-5 py-2" id="checkout-button" >Buy Now</button>

    

  <div class="product float-right"  style="position: relative; top:-787px">
    <button class="wishlist-button {% if flag %} added {% endif %}"  data-product-id="{{ img.id }}"><i class="fa fa-heart heart-icon"></i></button>

  </div>
    
  </div>
  <div class="col-sm-4">
    {{img.product.name}} <br />

    <b> Rs. {{img.product.price}} </b> <br />
    {{img.product.description}}
  </div>

  <div class="form-group">
    <label for="email" style="display:none;">Email: </label>
    <input style="display:none;" type="email" name="email" id="email" class="form-control" placeholder="Email">
</div> 

</div> <br><br>


{% comment %} add rattings   {% endcomment %}

 
 <h3 class="card-title">Avg rating:
    <span class="fa fa-star {% if average_rating > 0 %} checked {% endif %}"></span>
    <span class="fa fa-star {% if average_rating > 1 %} checked {% endif %}"></span>
    <span class="fa fa-star {% if average_rating > 2 %} checked {% endif %}"></span>
    <span class="fa fa-star {% if average_rating > 3 %} checked {% endif %}" ></span>
    <span class="fa fa-star {% if average_rating > 4 %} checked {% endif %}"></span>
</h3> 

{% comment %} <h3>Reviews:</h3>
{% for ratting in rattings %}
{{ratting.comments}} <br>

{% endfor %} {% endcomment %}

<div id="reviews">
    {% for comment in rattings %}
      <div class="review">{{ comment.comments }}</div>
    {% endfor %}
  </div>
  
  <button id="show-more">Show more</button>





<script>
  document.querySelectorAll('.wishlist-button').forEach(function(button) {
      button.addEventListener('click', function() {
          const productId = this.getAttribute('data-product-id');
          const action = this.classList.contains('added') ? 'remove' : 'add';
          console.log(productId)
          console.log(action)


          const csrfToken = getCookie('csrftoken');
          
          const headers = {
              'Content-Type': 'application/json',
              'X-CSRFToken': csrfToken,
          };

          if (action === 'add') {
              fetch(`/add_to_wishlist/${productId}/`, { method: 'POST', headers: headers })
              .then(response => response.json())
              .then(data => {
                  if (data.message === 'Item added to wishlist') {
                      this.classList.add('added');
                  }
              });
          } else if (action === 'remove') {
              fetch(`/remove_from_wishlist/${productId}/`, { method: 'POST', headers: headers })
              .then(response => response.json())
              .then(data => {
                  if (data.message === 'Item removed from wishlist') {
                      this.classList.remove('added');
                  }
              });
          }
      });
  });

  function getCookie(name) {
      const value = `; ${document.cookie}`;
      const parts = value.split(`; ${name}=`);
      if (parts.length === 2) return parts.pop().split(';').shift();
  }
  
</script>

{% comment %} payment scripts {% endcomment %}

<script src="https://js.stripe.com/v3/"></script>
<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('{{ stripe_publishable_key }}');
    var checkoutButton = document.getElementById('checkout-button');
    

    checkoutButton.addEventListener('click', function () {

    
        // Create a new Checkout Session using the server-side endpoint you
        // created in step 3.
        fetch("{% url 'api_checkout_session' id=img.product.id %}", {
            method: 'POST',
             body: JSON.stringify(
                { email: email }
            ) 
        })
            .then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.sessionId });
            })
            .then(function (result) {
                // If `redirectToCheckout` fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using `error.message`.
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error('Error:', error);
            });
    });
</script>

  {% comment %} show more review {% endcomment %}



<script>
    var page = 2;  // Initial page for loading more reviews
  
    $('#show-more').on('click', function() {
      $.ajax({
        url: '/show-more-review/',  // URL to fetch more reviews
        data: { page: page, prod_id:{{img.product.id}} },
        success: function(data) {
          if (data.reviews) {
            var $reviews = $('#reviews');
            for (var i = 0; i < data.reviews.length; i++) {
              var review = data.reviews[i];
              $reviews.append('<div class="review">' + review.text + '</div>');
            }
            page++;
          } else {
            $('#show-more').prop('disabled', true).text('No more reviews');
          }
        }
      });
    });
  </script>
  

  {% comment %} crasoul {% endcomment %}


<script>

var myCarousel = document.querySelector('#myCarousel')
var carousel = new bootstrap.Carousel(myCarousel, {
  interval: 100000
})

$('.carousel .carousel-item').each(function(){
    var minPerSlide = 4;
    var next = $(this).next();
    if (!next.length) {
    next = $(this).siblings(':first');
    }
    next.children(':first-child').clone().appendTo($(this));
    
    for (var i=0;i<minPerSlide;i++) {
        next=next.next();
        if (!next.length) {
            next = $(this).siblings(':first');
        }
        
        next.children(':first-child').clone().appendTo($(this));
      }
});


</script>
{% endblock product-details %}

customer/templates/customer/profile_information.html
{% extends "customer/base.html" %}

 {% block profile %}
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<div class="row">
    <div class="col-sm-3">
        {% include 'customer/profile_sidebar.html' %}
        
    </div>

    <div class="col-sm-9">
        <form action="" method="POST">
    {% csrf_token %}
    <div class="mt-5" style="text-align: center; background-color: azure;">
    {{form.as_p}}
    <input type="submit" value="Update" class="btn btn-primary">
    </div>
</form> 


    </div>
</div> 








{% endblock profile %}